name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the development dependencies
        run: uv sync --dev

      - name: Check linting and formatting
        run: uv run ruff check

      - name: Check types
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest
